# Generated by Django 3.0.5 on 2021-09-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тэга')),
                ('slug', models.SlugField(max_length=20, verbose_name='Слаг тэга')),
                ('hex_style', models.CharField(max_length=20, verbose_name='Цвет тега')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'hex_style', 'slug'), name='unique_tag'),
        ),
    ]
